const products=[
{id:1,name:'Premium Wireless Headphones',cat:'electronics',gender:'all',price:1299,old:1999,rating:4.4,reviews:12500,store:'Flipkart',icon:'🎧'},
{id:2,name:'Running Shoes — Comfort Edition',cat:'fashion',gender:'men',price:899,old:1499,rating:4.5,reviews:8700,store:'Amazon',icon:'👟'},
{id:3,name:'Minimal Analog Watch',cat:'fashion',gender:'women',price:499,old:999,rating:4.3,reviews:5200,store:'Myntra',icon:'⌚'},
{id:4,name:'Smart Fitness Band',cat:'electronics',gender:'all',price:799,old:1299,rating:4.2,reviews:9400,store:'Amazon',icon:'⌚'},
{id:5,name:'Everyday Cotton T-Shirt',cat:'fashion',gender:'men',price:299,old:599,rating:4.4,reviews:15300,store:'Myntra',icon:'👕'},
{id:6,name:'Wireless Neckband',cat:'electronics',gender:'all',price:649,old:1199,rating:4.1,reviews:22100,store:'Flipkart',icon:'🎶'},
{id:7,name:'Women Casual Sneakers',cat:'fashion',gender:'women',price:749,old:1399,rating:4.5,reviews:6800,store:'Myntra',icon:'👟'},
{id:8,name:'LED Study Lamp',cat:'electronics',gender:'all',price:399,old:799,rating:4.6,reviews:11800,store:'Amazon',icon:'💡'}
];
const drops=products.slice(0,6);
const grid=document.getElementById('productGrid'); const dropGrid=document.getElementById('dropGrid');
let currentFilter='all'; let currentBudget=null; let currentRating=null;
const money=n=>'₹'+n.toLocaleString('en-IN');
function card(p){const pct=Math.round((1-p.price/p.old)*100);return `<article class="product-card"><div class="product-img"><span class="badge">🔥 ${pct}% OFF</span>${p.icon}</div><div class="card-body"><h3>${p.name}</h3><div class="meta"><span class="stars">★ ${p.rating}</span> · ${p.reviews.toLocaleString('en-IN')} reviews</div><div class="product-price"><strong>${money(p.price)}</strong><del>${money(p.old)}</del></div><div class="save">↓ Save ${money(p.old-p.price)}</div><div class="card-bottom"><span class="store">${p.store}</span><button class="view" data-product="${p.id}">Compare</button></div></div></article>`}
function render(){let list=products.filter(p=>currentFilter==='all'||p.cat===currentFilter||p.gender===currentFilter);if(currentBudget)list=list.filter(p=>p.price<=currentBudget);if(currentRating)list=list.filter(p=>p.rating>=currentRating);const q=document.getElementById('searchInput').value.toLowerCase().trim();if(q)list=list.filter(p=>(p.name+' '+p.cat+' '+p.store).toLowerCase().includes(q));const sort=document.getElementById('sortSelect').value;list.sort((a,b)=>sort==='price'?a.price-b.price:sort==='rating'?b.rating-a.rating:sort==='reviews'?b.reviews-a.reviews:sort==='drop'?((b.old-b.price)-(a.old-a.price)):((b.rating*2+Math.log10(b.reviews))-(a.rating*2+Math.log10(a.reviews))));grid.innerHTML=list.length?list.map(card).join(''):'<div style="grid-column:1/-1;background:#fff;padding:35px;border-radius:18px;text-align:center;color:#6b7280">No matching products in this demo. Try another filter.</div>';document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>openProduct(Number(b.dataset.product)));}
function renderDrops(){dropGrid.innerHTML=drops.map(p=>{const pct=Math.round((1-p.price/p.old)*100);const bars=[75,65,55,48,42,32,25,18].map((h,i)=>`<i style="height:${h-i*2}px"></i>`).join('');return `<article class="drop-card"><div class="drop-card-top"><div class="drop-icon">${p.icon}</div><span class="drop-percent">↓ ${pct}%</span></div><h3>${p.name}</h3><div class="drop-line"><div><del>${money(p.old)}</del><strong>${money(p.price)}</strong></div><span class="drop-percent">Save ${money(p.old-p.price)}</span></div><div class="spark">${bars}</div><div class="meta">★ ${p.rating} · ${p.reviews.toLocaleString('en-IN')} reviews · ${p.store}</div></article>`}).join('')}
function openProduct(id){const p=products.find(x=>x.id===id);const prices=[['Amazon',p.price+100],['Flipkart',p.price],['Myntra',p.price+150]];document.getElementById('modalContent').innerHTML=`<p class="eyebrow orange">PRICE COMPARISON</p><h2>${p.icon} ${p.name}</h2><p>⭐ ${p.rating} · ${p.reviews.toLocaleString('en-IN')} reviews</p><div class="compare-modal">${prices.map((x,i)=>`<div class="${i===1?'lowest':''}"><span>${x[0]}</span><b>${money(x[1])}${i===1?' ✓ Lowest':''}</b></div>`).join('')}</div><p style="color:#139a61;font-weight:800">📉 Current price is ${Math.round((1-p.price/p.old)*100)}% below the earlier price.</p><button class="primary full" onclick="alert('Demo only — affiliate/store link will be connected later.')">View Store Deal</button>`;document.getElementById('modal').classList.add('open')}
document.getElementById('closeModal').onclick=()=>document.getElementById('modal').classList.remove('open');document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('open')};
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;currentBudget=null;currentRating=null;render()});
document.querySelectorAll('[data-budget]').forEach(b=>b.onclick=()=>{currentBudget=Number(b.dataset.budget);currentRating=null;currentFilter='all';document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));document.querySelector('.filter[data-filter="all"]').classList.add('active');document.getElementById('deals').scrollIntoView({behavior:'smooth'});render()});
document.querySelector('[data-rating]').onclick=()=>{currentRating=4;currentBudget=null;currentFilter='all';document.getElementById('deals').scrollIntoView({behavior:'smooth'});render()};document.querySelector('[data-section]').onclick=()=>document.getElementById('drops').scrollIntoView({behavior:'smooth'});document.getElementById('sortSelect').onchange=render;document.getElementById('searchBtn').onclick=()=>{document.getElementById('deals').scrollIntoView({behavior:'smooth'});render()};document.getElementById('searchInput').onkeydown=e=>{if(e.key==='Enter'){document.getElementById('deals').scrollIntoView({behavior:'smooth'});render()}};document.getElementById('clearFilters').onclick=()=>{currentFilter='all';currentBudget=null;currentRating=null;document.getElementById('searchInput').value='';document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));document.querySelector('.filter[data-filter="all"]').classList.add('active');render()};document.getElementById('compareDemo').onclick=()=>openProduct(1);
render();renderDrops();
